"""add size field to products

Revision ID: e0acc3ff73c9
Revises: d8b6bb3191f6
Create Date: 2026-07-24 18:56:31.957604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0acc3ff73c9'
down_revision: Union[str, Sequence[str], None] = 'd8b6bb3191f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'size')
    # ### end Alembic commands ###
